### ISSUE TITLE
Browser Console Logs containing structured JSON objects are returned as a String with text 'Object'

### ISSUE THREAD

**Issue by sandeepnagra** [browserstack/selenium-webdriver-ruby#2] opened 2018-03-21 19:35 UTC
OS:  OSX
Selenium Version:  3.8.0
Browser:  Chrome 65.0
Language: Ruby 2.4.1

I referred to this section of logging document - https://github.com/SeleniumHQ/selenium/wiki/Logging#log-message

I have a similar situation where I want to read the logs from console where some logs are in JSON format but using the command `@browser.manage.logs.get(:browser)` with browser logging prefs set to ALL, I do get all the logs but the objects within the log are returned as a string with text 'object'. There should be an option to get the logs in JSON format as well. It seems like they are converted to string based on what I see here - https://github.com/browserstack/selenium-webdriver-ruby/blob/0f1ba0689b6250a2f35f8911003310a54463fa32/lib/selenium/webdriver/common/log_entry.rb

**Comment by Jamie-** [comment] 2019-08-01 11:11
This isn't specific to Ruby so I'd be inclined to close this one and re-open the one in the main Selenium repo https://github.com/SeleniumHQ/selenium/issues/5658

I have the same problem in Python with Selenium.

Selenium 3.141.59
Python 2.7
Chrome 75.0.3770.142
Chromedriver 75.0.3770.140

My log looks like this:
```
State transition: [Media Device] Set Local Media Stream: From Object
```

Where it should actually look like this (`SNIP` is a placeholder where I've cut for brevity) as it does in the console.
```
Info 12:09:06.076 : State transition: [Media Device] Set Local Media Stream: From 
{
  "mediaDevices": {
SNIP
}
```

**Comment by Gorankempe** [comment] 2021-12-13 09:08
@Jamie- did you figure out a solution for this? I'm having this exact problem right now in Python.

**Comment by Jamie-** [comment] 2021-12-13 23:16
@Gorankempe I raised a chromedriver bug as it's clear the issue is further up the chain from selenium but it was closed as wontfix as they say "Object" is all Chrome gives them.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3052

I never got around to it, but I guess you could try raising a Chrome bug?

**Comment by francisf** [comment] 2022-01-31 12:49
closing as per Jamie's comment.

**Closed as completed by francisf** 2022-01-31 12:49 UTC
